version: 0.2

env:
  variables:
    NODE_ENV: dev

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo "Logging into Serverless Framework..."
      - npx serverless login
      - echo "Deploying the service..."
      - npx serverless deploy --region us-west-1 --stage $APP_ENV

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist

cache:
  paths:
    - node_modules/**/*