version: 0.2

env:
  variables:
    NODE_ENV: dev

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the project..."
      - npm run build

  post_build:
    commands:
      - echo "Running tests..."
      - npm test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist

cache:
  paths:
    - node_modules/**/*