version: 0.2

env:
  variables:
    NODE_ENV: dev

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node.js version:"
      - node --version
      - echo "NPM version:"
      - npm --version
      - echo "Installing dependencies..."
      - npm install
      - echo "Installing Serverless Framework v3..."
      - npm install -g serverless@3
      - echo "Adding node_modules/.bin to PATH..."
      - export PATH=$(pwd)/node_modules/.bin:$PATH
      - echo "Checking Serverless version..."
      - npx serverless --version

  build:
    commands:
      - echo Build started on `date`
      - echo "Current PATH:"
      - echo $PATH
      - echo "Deploying the service..."
      - serverless deploy --region us-west-1 --stage dev

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist

cache:
  paths:
    - node_modules/**/*